### ISSUE TITLE
Fix arguments 0 supports SH please

### ISSUE THREAD

**Issue by suntong** [chenzhch/shellc#10]
I know fixing arguments 0 supports BASH, but I found it doesn't work for sh:

```sh
$ cat test
#!/bin/sh

echo "\$@ is $@"
echo "command line: $0 $*"
echo "hello world"

$ shellc sh test -f BASH
Ok! Make binary by "cc test.c -O2 -o test.x"

cc test.c -O2 -o test.x

$ ./test.x a bc d
$@ is a bc d
command line: /proc/self/fd/3 a bc d
hello world
```

Am I doing anything wrong?

I was expecting that `$0` to be `./test.x`. 

Please double check. thx.

**Comment by suntong** [comment]
and I just tried `-f FISH` as well.

**Comment by suntong** [comment]
"closed this as completed"? Care to explain the solution??

**Comment by chenzhch** [comment]
fixing arguments 0 not supports SH.

**Comment by suntong** [comment]
THANKS!

**Comment by suntong** [comment]
I still think it should be fixed, but anyway, 

> -e option： Fix parameter 0 value by custom external file

that's the only thing I can find about using the - e option, how would it work?

Suppose the test.x is called 

- as `./test.x`
- as `/abs/path/test.x`
- as `test.x` and is launched from within PATH

how a custom external file can handle all such cases?

**Comment by chenzhch** [comment]
Use argv [0] to fix parameter 0, as follows:
[shellc@localhost test]$ cat t.sh
echo "arg0 is $var"      
[shellc@localhost test]$ cat f.txt
var=?;
[shellc@localhost test]$ shellc sh t.sh -e f.txt
Ok! Make binary by "cc t.sh.c -O2 -o t.sh.x"
[shellc@localhost test]$ cc t.sh.c -O2 -o t.sh.x
[shellc@localhost test]$ ./t.sh.x
arg0 is ./t.sh.x
[shellc@localhost test]$ cd ..
[shellc@localhost ~]$ ./test/t.sh.x
arg0 is ./test/t.sh.x 
[shellc@localhost ~]$

**Comment by suntong** [comment]
Oh, thanks for the explanation.
