### ISSUE TITLE
Wrong exit code for shellc binary scripts 

### ISSUE THREAD

**Issue by mahmoud1973** [chenzhch/shellc#12]
root@my:~/shellc# cat test2.sh
#!/bin/bash
exit 10
root@my:~/shellc# ./shellc bash test2.sh -s
Ok! Make binary by "cc test2.sh.c -O2 -o test2.sh.x"
root@my:~/shellc# cc test2.sh.c -O2 -o test2
root@my:~/shellc# ./test2
root@my:~/shellc#  echo $?
1

Using latest 1.4 version. Normal mode doesn't have this issue.

**Comment by xiaoM128** [comment]
Same problem

**Comment by chenzhch** [comment]
Version 1.5 has been fixed
