### ISSUE TITLE
解决安全模式引入外部标准参数出现“没有合并的右花括号”的问题

### ISSUE THREAD

**Issue by juxjamsjd** [chenzhch/shellc#18]
发现从1版本到现在最新的版本都没有修复的代码片段：
```c
fputs(" } ; ", pipe);
```
应该改成：
```
fputs("; } ; ", pipe);
```
函数末尾右花括号少了个“;”，居然都没人发现🤔
安全模式引入管道参数作为脚本源代码运行加密后就不支持管道参数了，但是正常模式就是临时加载到描述符运行应该可以支持管道参数的传入希望加上这一点。

**Comment by chenzhch** [comment]
特殊场景下确实存在这个BUG问题。

**Comment by chenzhch** [comment]
1.7版修复此BUG
