### ISSUE TITLE
busybox提供的sh无法执行会提示: applet not found

### ISSUE THREAD

**Issue by uosbox** [chenzhch/shellc#2]
bash没问题。busybox还无法支持

**Comment by chenzhch** [comment]
我在Ubuntu下如下操作成功
1、先创建符号链接（因Ubuntu有sh命令，busybox用ash)
sudo ln -s /usr/bin/busybox /usr/bin/ash
2、使用安全模式生成C代码（非安全模式会报applet not found）
shellc ash example.sh -s

**Comment by uosbox** [comment]
> 我在Ubuntu下如下操作成功 1、先创建符号链接（因Ubuntu有sh命令，busybox用ash） sudo ln -s /usr/bin/busybox /usr/bin/ash 2、使用安全模式生成C代码（非安全模式会报applet not found） shellc ash example.sh -s

我在ubuntu系统下面也成功了的，
奇怪的是在openwrt下面就上面的提示
即便我在openwrt装了bash也会爆错
-s 后不能带参数

**Comment by chenzhch** [comment]
如果在无-s选项，要对.c文件做些修改
if (!strcmp(command, "node")) {
        args[j++] = strdup(command);
        args[j++] = strdup("--preserve-symlinks-main");
    } else {
        //args[j++] = strdup(argv[0]);
        args[j++] = strdup(command);
        args[j++] = strdup("sh");
    }

**Comment by chenzhch** [comment]
-s 也是支持参数的，在Ubuntu上没问题，但openwr我没用过

**Comment by chenzhch** [comment]
-s 也是支持参数的，在Ubuntu上没问题，但openwr我没用过

**Comment by chenzhch** [comment]
-s 也是支持参数的，在Ubuntu上没问题，但openwr我没用过

**Comment by uosbox** [comment]
![image](https://github.com/chenzhch/shellc/assets/18119846/241e1ca7-05fd-4786-bc43-a27399f824cc)
上面这个图就是openwrt上的
![image](https://github.com/chenzhch/shellc/assets/18119846/6de57d36-4ff5-4378-98fd-8559a516d790)
这个图就是ubuntu上的 可以看出ash实际上是dash

**Comment by uosbox** [comment]
> 如果在无-s选项，要对.c文件做些修改 if (!strcmp(command, "node")) { args[j++] = strdup(command); args[j++] = strdup("--preserve-symlinks-main"); } else { //args[j++] = strdup(argv[0]); args[j++] = strdup(command); args[j++] = strdup("sh"); }

![image](https://github.com/chenzhch/shellc/assets/18119846/678dd1cd-4d97-4020-81f6-2b87a68edf4f)
改了之后不加-s就这错误

**Comment by chenzhch** [comment]
不要改shellc.c , 真接改脚本生成的C代码。

**Comment by chenzhch** [comment]
不要改shellc.c , 真接改脚本生成的C代码。另：安全模式改一下生成后的文件：pipe = popen("busybox sh", "w"); 试一下，如果还是不行，那估计是支持不了openwrt操作系统

**Comment by chenzhch** [comment]
不要改shellc.c , 真接改脚本生成的C代码。另：安全模式改一下生成后的文件：pipe = popen("busybox sh", "w"); 试一下，如果还是不行，那估计是支持不了openwrt操作系统

**Comment by chenzhch** [comment]
![image](https://github.com/chenzhch/shellc/assets/34769478/0b034bcf-67e2-45eb-8013-f9ff8414ce13)
这是openwrt的变种，直接用shellc sh test.sh -s 生成，不用改生成后的程序，没问题

**Comment by chenzhch** [comment]
![image](https://github.com/chenzhch/shellc/assets/34769478/40b562e0-5691-4a92-8495-813e0fb43389)
我在这个环境下测试了，没什么问题。你那个报错我怀疑你是在不同机器上编译生成可执行程序运行的结果。你可以用一个简单的C程序试一下，是不是也报语法错。

**Comment by chenzhch** [comment]
![image](https://github.com/chenzhch/shellc/assets/34769478/40b562e0-5691-4a92-8495-813e0fb43389)
我在这个环境下测试了，没什么问题。你那个报错我怀疑你是在不同机器上编译生成可执行程序运行的结果。你可以用一个简单的C程序试一下，是不是也报语法错。

**Comment by uosbox** [comment]
> ![image](https://private-user-images.githubusercontent.com/34769478/341088265-40b562e0-5691-4a92-8495-813e0fb43389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTg0MjgsIm5iZiI6MTcxODg1ODEyOCwicGF0aCI6Ii8zNDc2OTQ3OC8zNDEwODgyNjUtNDBiNTYyZTAtNTY5MS00YTkyLTg0OTUtODEzZTBmYjQzMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA0MzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYWYyYmM0ZThmMzg2MjliZTk4MWNhYjRiYjEwMjE5NThmMDE2MjhmM2MwNTc4NDM4ZjdmMzA3MzRkZDNiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eONgojOWQIe5nSRq0OaBFE-5tRM55MI4VZJVr4Nt3B0) 我在这个环境下测试了，没什么问题。你那个报错我怀疑你是在不同机器上编译生成可执行程序运行的结果。你可以用一个简单的C程序试一下，是不是也报语法错。

交叉编译的！！其他程序没问题！shc生成的c也没问题！！
但是shc的-H参数生成的就无法使用

**Comment by chenzhch** [comment]
shc -H 参数调用的是system命令，还是存在源码泄漏问题。你那个报错应该是在64位操作系统上生成32位程序引起的，V1.2增加了指定目标操作系统位数的功能，应该能解决报错问题了。

**Comment by uosbox** [comment]
> shc -H 参数调用的是system命令，还是存在源码泄漏问题。你那个报错应该是在64位操作系统上生成32位程序引起的，V1.2增加了指定目标操作系统位数的功能，应该能解决报错问题了。

1.2版本确实解决这个问题！不过busybox必须得带上-s
-b 参数确定目标运行环境的位数，这个能不能像shc生成的一样可以自动识别

已经解决了很大的问题 谢谢
