### ISSUE TITLE
What is Xbash and How to use it

### ISSUE THREAD

**Issue by mahmoud1973** [chenzhch/shellc#24]
Hello,

Thank you for the great work on shellc! I noticed in the documentation for new version 1.8 that the -x option can be used when the script file is a binary generated by xbash. However, I'm having trouble finding more information about xbash itself.

Could you please clarify the following?

1. What is xbash, and where can it be found or downloaded?

2. Can you please give example usage command for -x and - i together ? Your help page is not clear enough.

Thanks

**Comment by chenzhch** [comment]
bash enhanced tools  https://github.com/chenzhch/xbash

**Comment by scriptvpskita** [comment]
you didn't answer no.2 questions 

i try use xbash -X test
output compiler
test.x

then i use your script
shellc sh test.x -X
output
Error: test.x is not in xbash format
