### ISSUE TITLE
shellc v1.8.1 missing example for -f fix format usage

### ISSUE THREAD

**Issue by gdha** [chenzhch/shellc#25]
```bash
shellc sh /tmp/t.sh -f "arg0=?;"
Error: invalid fix format arg0=?
```
Could you please give an example of a correct format usage?

**Comment by chenzhch** [comment]
Fix arguments

Fix arguments 0 supports BASH, FISH, ZSH, PERL, PYTHON, JAVASCRIPT, LUA, RUBY.

In addition to built-in fix format, external file can also be used to fix arguments 0. File format：?Indicates parameter 0 value, line breaks must be explicitly used\n, Double quotes require an escape character \.Reference test/fix.txt.
