### ISSUE TITLE
how to use xbash with shellc ?

### ISSUE THREAD

**Issue by scriptvpskita** [chenzhch/shellc#26]
i try use xbash -X test
output compiler
test.x

then i use your script
shellc sh test.x -x
output
Error: test.x is not in xbash format

**Comment by chenzhch** [comment]
-x option： The script file is a non shebang binary file generated by [xbash](https://github.com/chenzhch/xbash).
[shellc@localhost ~]$ cat a.sh
echo "xbash test"     
[shellc@localhost ~]$ ./xbash_linux_x86-64 -X a.sh
Ok! Make file a.sh.x  
[shellc@localhost ~]$ ./shellc ./xbash_linux_x86-64 -x a.sh.x 
Ok! You can make binary by "cc a.sh.x.c -s -O2 -o a.sh.x.x -lpthread"
[shellc@localhost ~]$ cc a.sh.x.c -s -O2 -o a.sh.x.x -lpthread
[shellc@localhost ~]$ ./a.sh.x.x
https://github.com/chenzhch/xbash.git  
The program is compiled by xbash       
xbash test
[shellc@localhost ~]$

**Comment by chenzhch** [comment]
Fixed, re download xbash and regenerate the .x file
