### ISSUE TITLE
最新版对CSH的代码貌似有点问题？

### ISSUE THREAD

**Issue by mengxin523** [chenzhch/shellc#3]
#! /bin/csh
set Base64="DDL";
set sql = "update usr02 set accnt = '${Base64}' where mandt = '300' and bname = 'BASIS';"
echo $sql
echo "OK"

![ShareX-2024-06-25 09-09-57 2985](https://github.com/chenzhch/shellc/assets/39935125/afea2cc7-7ce7-46ad-b32a-d254201b33b3)

上面原始的.sh 可以运行，但是加密之后就运行不了了！
感谢！

**Comment by chenzhch** [comment]
我测试了，没发现你说的问题。生成C代码时要用csh，如下：
shellc csh Base64.sh

**Comment by mengxin523** [comment]
果然生成C代码的时候要用csh，感谢指导！！！
