### ISSUE TITLE
user input bug with shellc

### ISSUE THREAD

**Issue by mahmoud1973** [chenzhch/shellc#8]
Sample code :

#!/bin/bash

if [[ -t 0 ]]; then
    read -p "Do you want to proceed? (yes/no) " user_input
else
    echo "No terminal detected. Exiting."
    exit 1
fi

if [[ "$user_input" == "yes" ]]; then
    echo "Yes..do something.. please wait.."
else
    echo "cancelled. Exiting."
    exit 0
fi

I Always get no terminal detected with shellc ... I used the same code with shc and it works with no issues

I'm using : 
./shellc bash test.sh -s
cc test.sh.c -O2 -o test.sh.x

**Comment by chenzhch** [comment]
The safe mode human-machine interaction needs to be modified to read from the device /dev/tty. such as shell script read input needs to be changed to read input</dev/tty, For other languages, refer to the test/test_input.*. The normal mode does not require code modification.

**Comment by chenzhch** [comment]
safe mode not support, use  normal mode:
./shellc bash test.sh

**Comment by mahmoud1973** [comment]
> safe mode not support, use normal mode: ./shellc bash test.sh

I used this :

>>>>>>>>
#!/bin/bash

# Prompt the user for input and read from /dev/tty
echo "Do you want to proceed? (yes/no): "
read user_input </dev/tty

if [[ "$user_input" == "yes" ]]; then
    echo "Yes..do something.. please wait.."
else
    echo "Cancelled. Exiting."
    exit 0
fi
>>>>>>

and commands :
./shellc bash test.sh -s
cc test.sh.c -O2 -o test.sh.x

and it worked good with Safe mode .. didn't try any advanced scripts yet .. do you think it's not gonna work with safe mode ?

**Comment by chenzhch** [comment]
NO.  After compilation, if [[- t 0]] always returns a value of False.

**Comment by chenzhch** [comment]
NO. In safe mode, if [[- t 0]] always returns a value of False. In safe mode，The actual executed command is：cat test.sh |bash
