### ISSUE TITLE
Memory leak test report please

### ISSUE THREAD

**Issue by suntong** [chenzhch/shellc#9]
I don't quite understand the report in https://github.com/neurobin/shc/issues/155, but would you try to

compiled [shellc](https://github.com/chenzhch/shellc) in afl-gcc and fsanitize mode then convert  a script to an executable file and execute it and see what you get please?

and run through cppcheck as well please. thx

(I'm the DM of the shc Debian package, and shc is not compiling under it, see its # 167, the author is not responding thus I'm personally looking for an alternate. Looking forward to your Memory leak test report. thx).

**Comment by chenzhch** [comment]
This is not shellc problem.

**Comment by suntong** [comment]
How can you tell and be so sure that shellc have no such problem?
Why closing it without even providing any proof?

**Comment by chenzhch** [comment]
shellc@localhost:~> ./shellc sh t.sh -s
Ok! Make binary by "cc t.sh.c -O2 -o t.sh.x"
shellc@localhost:~> cppcheck t.sh.c
Checking t.sh.c ...
Active checkers: 40/565
shellc@localhost:~> ./shellc sh t.sh -s -f BASH
Ok! Make binary by "cc t.sh.c -O2 -o t.sh.x"
shellc@localhost:~> cppcheck t.sh.c
Checking t.sh.c ...
Active checkers: 40/565
shellc@localhost:~> ./shellc sh t.sh -s -e f.txt
Ok! Make binary by "cc t.sh.c -O2 -o t.sh.x"
shellc@localhost:~> cppcheck t.sh.c
Checking t.sh.c ...
Active checkers: 40/565
shellc@localhost:~> cppcheck shellc.c
Checking shellc.c ...
Active checkers: 40/565
shellc@localhost:~>
Although version 1.3 prompts a memory leak, the leaked content is "Failed to pipe" and will not leak script code.

**Comment by suntong** [comment]
Thanks for doing the memory leak checking and provide an updated version.

That's doing cppcheck. Would you try to compile it in afl-gcc and fsanitize mode and check the results as well? -- not believing that it'll find any new leaks, but just to provide full coverage. Thanks.

**Comment by chenzhch** [comment]
Memory leak test report
[test.txt](https://github.com/user-attachments/files/17704274/test.txt)
